### ISSUE TITLE
Not functional anymore?

### ISSUE THREAD

**Issue by jp1995** [TheBlackParrot/discord-mpd-presence#1]
Hey. You've probably forgotten about this little thing, but I've got a question. I know discord has gone through a lot of changes recently, is this script still functional for you?

I'm asking because I've seemingly got it [up and running,](https://i.imgur.com/jaUY6Av.png) but my status in discord does not change.

Also, in your example settings file, there's a comma at the end of the token line which throws syntax errors. :P

**Comment by TheBlackParrot** [comment]
I imagine discord.io changed a bit and broke something. I imagine it's not that hard of a fix so I'll look into it at some point.

**Comment by jp1995** [comment]
I have technically resolved the problem now. I looked into the discord.io documentation and had a chat with someone on their discord and I think the code is still fine. 

I did, however, find a closed issue on github with someone with my exact problem. Apparently, with client.setPresence, your status is updated and everyone else can see it, but you can't. I've verified this by just quickly creating a second account.

I was wondering, was this ever the case for you? Or is this a recent development? 

As far as I know, there's no way to make the status appear for yourself as well.

**Comment by TheBlackParrot** [comment]
Ah yeah I asked the same question actually, you have to use an alternate account if you want to see it for yourself.
